config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'splash#index'
  root to: 'categories#index'
  get 'categories/:category_id/entities', to: 'entities#index'
  get 'categories/new', to: 'categories#new'
  get 'entities/new', to: 'entities#new'
  post 'entities/create', to: 'entities#create'
  post 'categories/create', to: 'categories#create'
  post 'entities/add_cat', to: 'entities#add_cat'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # can :read, Category

    return unless user.present?

    can %i[read destroy create], Category, user: user
    can %i[read destroy create], Entity, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :category_with_entities
  belongs_to :user
end

app/models/category_with_entity.rb
class CategoryWithEntity < ApplicationRecord
  belongs_to :category
  belongs_to :entity

  after_validation :update_total_amount

  def update_total_amount
    cat = Category.find(category_id)
    ent = Entity.find(entity_id)
    cat.update(total_amount: cat.total_amount + ent.amount)
  end
end

app/models/entity.rb
class Entity < ApplicationRecord
  validates :name, :amount, presence: true

  has_many :category_with_entities
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :entities, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :checking

  def checking
    redirect_to(welcome_path) unless user_signed_in?
  end

  def index
    @categories = Category.where(user_id: current_user.id).order(updated_at: :desc)
  end

  def create
    @category = Category.new
    @category.user_id = current_user.id
    @category.name = params[:name]
    @category.icon = params[:icon]
    redirect_to(root_path, notice: 'category created succesfully') if @category.save
  end

  def new; end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  def index
    @category = Category.find(params[:category_id])
    if can? :read, @category
      @entities = @category.category_with_entities.order(created_at: :desc)
      @total_amount = @category.total_amount

    else
      redirect_to(root_path, notice: 'you dont have access')
    end
  end

  def create
    choose = params[:choose]
    @entity = Entity.new
    @entity.user_id = current_user.id
    @entity.name = params[:name]
    @entity.amount = params[:amount]
    if choose.nil?
      flash.alert = 'you have to pick atleast one category'
      redirect_to(entities_new_path)
    end

    return unless @entity.save

    choose.each do |choice|
      category_with_entity = CategoryWithEntity.new
      category_with_entity.category = Category.find(choice)
      category_with_entity.entity = Entity.find(@entity.id)
      category_with_entity.save
    end
    redirect_to(root_path)
  end

  def new
    @categories = Category.where(user_id: current_user.id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/index.html.erb
<div class='container'>
  <header class='header'>
    <div class='header-space'>
      
    </div>
    <div>
      <h1 class='header-title'>Categories</h1>
    </div>
    <%= link_to("Logout", destroy_user_session_path, method: :delete, class: 'log-out')%>
  </header>
  <div class="content">
    

    <% @categories.each do |category|%>
      <div class='category'>
        <%= image_tag category.icon, class: 'cat_icon'%>
        <div class='cat_details'>
          <a class='cat_name' href="categories/<%= category.id %>/entities">
            <%= category.name%> 
          </a>
          <div class='cat_div'> 
            <p><%= category.created_at.strftime("%d %b %Y") %></p>
            <p><%= category.total_amount%> $</p>
          </div>
        </div>
      </div>
    <%end%>

  </div>
  <footer class='footer'>
    <%= link_to("Create Category", categories_new_path, class: 'bottom_create')%>
  </footer>
</div

app/views/categories/new.html.erb
<div class='form-page'>
  <%= form_with model: @category, url: categories_create_path do |form|%>
    <div class="form-container">
      <h2>Create a new category</h2>
      <div class='field'>
        <%= form.label :name, 'Name' %>
        <%= form.text_field :name, class: 'input' %>
      </div>

      <div class='field'>
        <%= form.label :icon, 'Icon' %>
        <%= form.url_field :icon, class: 'input'%>
      </div>

      <div>
        <%= form.submit "Submit", class: 'create-btn'%>
      </div>
      <div class='go-back'>
        <a href= javascript:history.back() class='delete-btn'>
          Go Back
        </a>
      </div>
    </div>
  <% end %>
</div>

app/views/entities/index.html.erb
<div class='container'>
  <header class='header'>
    <div>
      <%= link_to" < ", root_path, class: 'back'%>
    </div>
    <div>
      <h1 class='header-title'>Transactions</h1>
    </div>
    <%= link_to("Logout", destroy_user_session_path, method: :delete, class: 'log-out')%>
  </header>
  <div class='total'>
    <p>Total amount</p>
    <p><%= @total_amount %> $</p>
  </div>
  <div class="content">

    <% @entities.each do |entity|%>
      <div class='entity'>
        <p class='cat_name'> <%= entity.entity.name %></p>
        <p class='cat_name'> <%= entity.entity.amount %>$ </p>
      </div>
    <%end%>
    

  </div>
  <footer class='footer'>
    <%= link_to("Create Transaction", entities_new_path, class: 'bottom_create')%>
  </footer>
</div

app/views/entities/new.html.erb
<header class='header'>
  <div>
    <%= link_to" < ", root_path, class: 'back'%>
  </div>
  <div>
    <h1 class='header-title'>creare transaction</h1>
  </div>
  <%= link_to("Logout", destroy_user_session_path, method: :delete, class: 'log-out')%>
</header>
<div class='form-page'>
  <div class="modal-background">
    <div class="modal">
      <div class="modal-header">
        <h2 class="modal-title">Add a Category</h2>
        <div class="X">
          <p >X</p>
        </div>
      </div>
      <div class='modal-body'>
        <h3>Choose a category</h3>
        <%= form_with  url: entities_add_cat_path do |form| %>
          <%= form.label :category_list %>
          <%= form.collection_select :category_list, @categories ,:id , :name %>
          <%= form.submit "add", class: "create-btn" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="form-container">
    <%= form_with model: @entity, url: entities_create_path do |form|%>
      <h2>Create a new Transaction</h2>
      <div class='field'>
        <%= form.label :name, 'Name' %>
        <%= form.text_field :name, class: 'input' %>
      </div>

      <div class='field'>
        <%= form.label :amount, 'Amount($)' %>
        <%= form.number_field :amount, class: 'input' %>
      </div>

      <div class='field'>
         <%= form.label :cat, 'Select a category' %>
          <%@categories.each do |categ|%>
          <div class='checkdiv'>
            <%= form.label  categ.name %>
            <%= check_box_tag "choose[]", categ.id %>
          </div>
          <%end%>
      </div>

      <div>
        <%= form.submit "Submit", class: 'create-btn'%>
      </div>
      <div class='go-back'>
        <a href= javascript:history.back() class='delete-btn'>
          Go Back
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
   <%#  <% flash.each do |name, message| %>
   <%#    <div class="<%= name %>  <%#       "><%= message %>           <%# </div>
   <%#  <% end %>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class='splash-page'>  
  <div class='welcome'>
    <h2>Welcome to MBA</h2>
    <p>My budget App</p>
  </div>

  <%= link_to("Login", new_user_session_path, class: 'log-in')%>
  <%= link_to("SignUp", new_user_registration_path, class: 'sign_in')%>
</div>